[package]
name = "fr-pm-jack-connection-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
dashmap = "6.0.1"
itertools = "0.13.0"
pipewire = "0.8.0"
log = "0.4.22"
futures = "0.3.30"
async-std = "1.12.0"
